---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 8-demo-kustomize-git-bb-app
  namespace: flux-system
spec:
  interval: 1m40s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-course-udemy-flux-cd-101-with-hands-on-labs-bb-app-source
  targetNamespace: 8-demo
